service:
  port: 8080
  mode: debug
  write_timeout: 60
  read_timeout: 60
  close_timeout: 5
  limit_number: 100

log:
  level: debug
  file_path: logs/app.log

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: w2learn
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 3600
  log_level: info
  auto_migrate: true