service:
  port: 8080
  mode: debug
  write_timeout: 60
  read_timeout: 60
  close_timeout: 5
  limit_number: 100

log:
  level: debug
  file_path: logs/app.log

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: w2learn
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 3600
  log_level: info
  auto_migrate: true

redis:
  addr: localhost:6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5
  read_timeout: 5
  write_timeout: 5

jwt:
  secret: 0cae99d4c2c8711efadecf03a20b9f6c98bc1a7a885122d3a9a0f6eeed2c9636